# BatGlass configuration

gemini:
  model: gemini-3.1-flash-lite-preview

ocr:
  max_tokens: 160

scene:
  max_tokens: 60

tts:
  model: models/piper/en_US-ryan-low.onnx
  audio_device: plughw:wm8960soundcard

stt:
  model: whisper.cpp/models/ggml-base.en.bin
  audio_device: hw:wm8960soundcard
  threads: 4
